# Constants
TOTAL_CALORIES_IN_KG = 7700
NUM_OF_DAYS = 7
ROUND_DECIMAL_PLACES = 2
LIST_IS_NOT_EMPTY = 1
FIRST_ELEMENT = 0
LAST_ELEMENT = -1
SECOND_TO_LAST_ELEMENT = -2
DEFAULT_DIFCIT = 0
DEFAULT_CALORIES = 0

# BMR
BMR_BASE_FEMALE = 655
BMR_BASE_MALE = 66
BMR_WEIGHT_FACTOR_FEMALE = 9.6
BMR_WEIGHT_FACTOR_MALE = 13.8
BMR_HEIGHT_FACTOR_FEMALE = 1.8
BMR_HEIGHT_FACTOR_MALE = 5
BMR_AGE_FACTOR_FEMALE = 4.7
BMR_AGE_FACTOR_MALE = 6.8

# Gender
FEMALE_GENDER = 0
MALE_GENDER = 1

# Activity Score
EASY_ACTIVE_SCORE = 1
MODERATELY_ACTIVE_SCORE = 2
VERY_ACTIVE_SCORE = 3
EXTRAORDINARY_ACTIVE_SCORE = 4

# Activity Factor
EASY_ACTIVE_FACTOR = 1.2
MODERATELY_ACTIVE_FACTOR = 1.375
VERY_ACTIVE_FACTOR = 1.725
EXTRAORDINARY_ACTIVE_FACTOR = 1.9