name: notification_repository

description: Dart package which manages the notifications.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  uuid: ^4.0.0

  # Firebase
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.1.0
  firebase_core: ^2.9.0
  
  timezone: ^0.9.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
